language: csharp
solution: SimpleMath.sln
install:
   - sudo apt-get install nunit-console
   - nuget restore SimpleMath.sln
script:
  - xbuild /p:Configuration=Release SimpleMath.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe SimpleMath.Test/bin/Release/SimpleMath.Test.dll
